
FROM centos:8

RUN dnf -y install epel-release && \
    dnf -y install wget && \
    dnf -y install gcc gcc-c++ make
RUN wget https://download.arangodb.com/arangodb39/rpm/centos/8/x86_64/arangodb3-3.9.2-1.x86_64.rpm && \
    dnf -y install arangodb3-3.9.2-1.x86_64.rpm && \
    rm -f arangodb3-3.9.2-1.x86_64.rpm
EXPOSE 8529
CMD ["arangod"]