services:
  cratedb01:
    container_name: cratedb-node1
    image: crate:latest
    ports:
      - "4201:4200"
    volumes:
      - ./data/cratedb/01:/data  # Montar el directorio data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb01",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb02,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=2"]
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g
    networks:
      - khab-network

  cratedb02:
    container_name: cratedb-node2
    image: crate:latest
    ports:
      - "4202:4200"
    volumes:
      - ./data/cratedb/02:/data  # Montar el directorio data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb02",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb03",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=2"]
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g
    networks:
      - khab-network

  cratedb03:
    container_name: cratedb-node3
    image: crate:latest
    ports:
      - "4203:4200"
    volumes:
      - ./data/cratedb/03:/data  # Montar el directorio data
    command: ["crate",
              "-Ccluster.name=crate-docker-cluster",
              "-Cnode.name=cratedb03",
              "-Cnode.data=true",
              "-Cnetwork.host=_site_",
              "-Cdiscovery.seed_hosts=cratedb01,cratedb02",
              "-Ccluster.initial_master_nodes=cratedb01,cratedb02,cratedb03",
              "-Cgateway.expected_data_nodes=3",
              "-Cgateway.recover_after_data_nodes=2"]
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g
    networks:
      - khab-network

  orientdb-node1:
    image: orientdb:latest
    container_name: orientdb-node1
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENTDB_NODE_NAME=orientdb-node1
      - ORIENTDB_HOME=/orientdb
    volumes:
      - ./config/orientdb-server-config-node1.xml:/orientdb/config/orientdb-server-config.xml
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/hazelcast.xml:/orientdb/config/hazelcast.xml
      - ./data:/data  # Montar el directorio data
    ports:
      - "2424:2424"
      - "2480:2480"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    networks:
      - khab-network

  orientdb-node2:
    image: orientdb:latest
    container_name: orientdb-node2
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENTDB_NODE_NAME=orientdb-node2
      - ORIENTDB_HOME=/orientdb
    volumes:
      - ./config/orientdb-server-config-node2.xml:/orientdb/config/orientdb-server-config.xml
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/hazelcast.xml:/orientdb/config/hazelcast.xml
      - ./data:/data  # Montar el directorio data
    ports:
      - "2425:2424"
      - "2481:2480"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    networks:
      - khab-network

  orientdb-node3:
    image: orientdb:latest
    container_name: orientdb-node3
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENTDB_NODE_NAME=orientdb-node3
      - ORIENTDB_HOME=/orientdb
    volumes:
      - ./config/orientdb-server-config-node3.xml:/orientdb/config/orientdb-server-config.xml
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/hazelcast.xml:/orientdb/config/hazelcast.xml
      - ./data:/data  # Montar el directorio data
    ports:
      - "2426:2424"
      - "2482:2480"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    networks:
      - khab-network

  orientdb-node4:
    image: orientdb:latest
    container_name: orientdb-node4
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - ORIENTDB_NODE_NAME=orientdb-node4
      - ORIENTDB_HOME=/orientdb
    volumes:
      - ./config/orientdb-server-config-node4.xml:/orientdb/config/orientdb-server-config.xml
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/hazelcast.xml:/orientdb/config/hazelcast.xml
      - ./data:/data  # Montar el directorio data
    ports:
      - "2427:2424"
      - "2483:2480"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    networks:
      - khab-network

  agent1:
    container_name: arangodb-agent1
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod 
      - --server.endpoint=tcp://0.0.0.0:5101
      - --agency.my-address=tcp://agent1:5101
      - --agency.activate=true
      - --agency.size=3
      - --agency.endpoint=tcp://agent1:5101
      - --agency.endpoint=tcp://agent2:5102
      - --agency.endpoint=tcp://agent3:5103
      - --agency.supervision=true
      - --database.directory=/var/lib/arangodb3/agent1
    ports:
      - "5101:5101"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.25"
    volumes:
      - ./data:/data
    networks:
      - khab-network

  agent2:
    container_name: arangodb-agent2
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:5102
      - --agency.my-address=tcp://agent2:5102
      - --agency.activate=true
      - --agency.size=3
      - --agency.endpoint=tcp://agent1:5101
      - --agency.endpoint=tcp://agent2:5102
      - --agency.endpoint=tcp://agent3:5103
      - --agency.supervision=true
      - --database.directory=/var/lib/arangodb3/agent2
    ports:
      - "5102:5102"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.25"
    volumes:
      - ./data:/data
    networks:
      - khab-network

  agent3:
    container_name: arangodb-agent3
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:5103
      - --agency.my-address=tcp://agent3:5103
      - --agency.activate=true
      - --agency.size=3
      - --agency.endpoint=tcp://agent1:5101
      - --agency.endpoint=tcp://agent2:5102
      - --agency.endpoint=tcp://agent3:5103
      - --agency.supervision=true
      - --database.directory=/var/lib/arangodb3/agent3
    ports:
      - "5103:5103"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.25"
    volumes:
      - ./data:/data
    networks:
      - khab-network

  dbserver1:
    container_name: arangodb-dbserver1
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:6101
      - --cluster.my-address=tcp://dbserver1:6101
      - --cluster.my-role=PRIMARY
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/dbserver1
    ports:
      - "6101:6101"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    volumes:
      - ./data:/data
    networks:
      - khab-network

  dbserver2:
    container_name: arangodb-dbserver2
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:6102
      - --cluster.my-address=tcp://dbserver2:6102
      - --cluster.my-role=PRIMARY
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/dbserver2
    ports:
      - "6102:6102"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    volumes:
      - ./data:/data
    networks:
      - khab-network

  dbserver3:
    container_name: arangodb-dbserver3
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:6103
      - --cluster.my-address=tcp://dbserver3:6103
      - --cluster.my-role=PRIMARY
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/dbserver3
    ports:
      - "6103:6103"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
    volumes:
      - ./data:/data
    networks:
      - khab-network

  # dbserver4:
  #   container_name: arangodb-dbserver4
  #   image: arangodb:latest
  #   environment:
  #     - ARANGO_NO_AUTH=1
  #   command:
  #     - arangod
  #     - --server.endpoint=tcp://0.0.0.0:6104
  #     - --cluster.my-address=tcp://dbserver4:6104
  #     - --cluster.my-role=PRIMARY
  #     - --cluster.agency-endpoint=tcp://agent1:5101
  #     - --cluster.agency-endpoint=tcp://agent2:5102
  #     - --cluster.agency-endpoint=tcp://agent3:5103
  #     - --database.directory=/var/lib/arangodb3/dbserver4
  #   ports:
  #     - "6104:6104"
  #   deploy:
  #    resources:
  #     limits:
  #       memory: 1g
  #       cpus: "0.5"
  #   volumes:
  #     - ./data:/data
  #   networks:
  #     - khab-network

  coordinator1:
    container_name: arangodb-coordinator1
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:7101
      - --cluster.my-address=tcp://coordinator1:7101
      - --cluster.my-role=COORDINATOR
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/coordinator1
    ports:
      - "7101:7101"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "0.5"
    volumes:
      - ./data:/data
    networks:
      - khab-network

  coordinator2:
    container_name: arangodb-coordinator2
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:7102
      - --cluster.my-address=tcp://coordinator2:7102
      - --cluster.my-role=COORDINATOR
      - --cluster.agency-endpoint=tcp://agent1:5101
      - --cluster.agency-endpoint=tcp://agent2:5102
      - --cluster.agency-endpoint=tcp://agent3:5103
      - --database.directory=/var/lib/arangodb3/coordinator2
    ports:
      - "7102:7102"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "0.5"
    volumes:
      - ./data:/data
    networks:
      - khab-network

networks:
  khab-network:
    driver: bridge
