CONNECT remote:192.168.50.101/KhaBench root rootpwd;
ALTER DATABASE TIMEZONE UTC
ALTER DATABASE DATETIMEFORMAT 'yyyy-MM-dd HH:mm:ss'
ALTER DATABASE DATEFORMAT 'yyyy-MM-dd'

--  Crear Clusters 
CREATE CLUSTER vendor_global_cluster; -- ID: 18

CREATE CLUSTER customer_global_cluster; -- ID: 19 
CREATE CLUSTER customer_north_cluster; -- ID: 20
CREATE CLUSTER customer_center_cluster; -- ID: 21
CREATE CLUSTER customer_south_cluster; -- ID: 22

CREATE CLUSTER product_global_cluster; -- ID: 23
CREATE CLUSTER product_cheap_cluster; -- ID: 24
CREATE CLUSTER product_expensive_cluster; -- ID: 25

CREATE CLUSTER order_pre_pandemic_cluster; -- ID: 26


CREATE CLUSTER person_global_cluster; -- ID: 27
CREATE CLUSTER person_north_cluster; -- ID: 28
CREATE CLUSTER person_center_cluster; -- ID: 29
CREATE CLUSTER person_south_cluster; -- ID: 30

CREATE CLUSTER tag_global_cluster; -- ID: 31

CREATE CLUSTER post_global_cluster; -- ID: 32


CREATE CLUSTER customer_knows_person_global_cluster; -- ID: 33
CREATE CLUSTER post_has_tag_global_cluster; -- ID: 34

CREATE CLUSTER person_global_has_interest_tag_cluster; -- ID: 35
CREATE CLUSTER person_north_has_interest_tag_cluster; -- ID: 36
CREATE CLUSTER person_center_has_interest_tag_cluster; -- ID: 37
CREATE CLUSTER person_south_has_interest_tag_cluster; -- ID: 38


CREATE CLUSTER post_has_creator_person_global_cluster; -- ID: 39
CREATE CLUSTER post_has_creator_person_north_cluster; -- ID: 40
CREATE CLUSTER post_has_creator_person_center_cluster; -- ID: 41
CREATE CLUSTER post_has_creator_person_south_cluster; -- ID: 42

--  **Crear Clases Globales con Propiedades, Restricciones y LINKS**


CREATE CLASS CUSTOMER EXTENDS V CLUSTER 19;
CREATE PROPERTY CUSTOMER.CUSTOMER_ID STRING;
ALTER PROPERTY CUSTOMER.CUSTOMER_ID MANDATORY TRUE;
ALTER PROPERTY CUSTOMER.CUSTOMER_ID NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.FIRST_NAME STRING;
ALTER PROPERTY CUSTOMER.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.LAST_NAME STRING;
ALTER PROPERTY CUSTOMER.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.GENDER STRING;
ALTER PROPERTY CUSTOMER.GENDER NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.BIRTHDAY DATE;
ALTER PROPERTY CUSTOMER.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.CREATE_DATE DATETIME;
ALTER PROPERTY CUSTOMER.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.LOCATION_IP STRING;
ALTER PROPERTY CUSTOMER.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.BROWSER_USED STRING;
ALTER PROPERTY CUSTOMER.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY CUSTOMER.PLACE INTEGER;
ALTER PROPERTY CUSTOMER.PLACE NOTNULL TRUE;

CREATE CLASS CUSTOMER_NORTH EXTENDS V CLUSTER 20;
CREATE PROPERTY CUSTOMER_NORTH.CUSTOMER_ID STRING;
ALTER PROPERTY CUSTOMER_NORTH.CUSTOMER_ID MANDATORY TRUE;
ALTER PROPERTY CUSTOMER_NORTH.CUSTOMER_ID NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.FIRST_NAME STRING;
ALTER PROPERTY CUSTOMER_NORTH.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.LAST_NAME STRING;
ALTER PROPERTY CUSTOMER_NORTH.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.GENDER STRING;
ALTER PROPERTY CUSTOMER_NORTH.GENDER NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.BIRTHDAY DATE;
ALTER PROPERTY CUSTOMER_NORTH.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.CREATE_DATE DATETIME;
ALTER PROPERTY CUSTOMER_NORTH.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.LOCATION_IP STRING;
ALTER PROPERTY CUSTOMER_NORTH.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.BROWSER_USED STRING;
ALTER PROPERTY CUSTOMER_NORTH.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_NORTH.PLACE INTEGER;
ALTER PROPERTY CUSTOMER_NORTH.PLACE NOTNULL TRUE;

CREATE CLASS CUSTOMER_CENTER EXTENDS V CLUSTER 21;
CREATE PROPERTY CUSTOMER_CENTER.CUSTOMER_ID STRING;
ALTER PROPERTY CUSTOMER_CENTER.CUSTOMER_ID MANDATORY TRUE;
ALTER PROPERTY CUSTOMER_CENTER.CUSTOMER_ID NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.FIRST_NAME STRING;
ALTER PROPERTY CUSTOMER_CENTER.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.LAST_NAME STRING;
ALTER PROPERTY CUSTOMER_CENTER.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.GENDER STRING;
ALTER PROPERTY CUSTOMER_CENTER.GENDER NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.BIRTHDAY DATE;
ALTER PROPERTY CUSTOMER_CENTER.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.CREATE_DATE DATETIME;
ALTER PROPERTY CUSTOMER_CENTER.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.LOCATION_IP STRING;
ALTER PROPERTY CUSTOMER_CENTER.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.BROWSER_USED STRING;
ALTER PROPERTY CUSTOMER_CENTER.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_CENTER.PLACE INTEGER;
ALTER PROPERTY CUSTOMER_CENTER.PLACE NOTNULL TRUE;

CREATE CLASS CUSTOMER_SOUTH EXTENDS V CLUSTER 22;
CREATE PROPERTY CUSTOMER_SOUTH.CUSTOMER_ID STRING;
ALTER PROPERTY CUSTOMER_SOUTH.CUSTOMER_ID MANDATORY TRUE;
ALTER PROPERTY CUSTOMER_SOUTH.CUSTOMER_ID NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.FIRST_NAME STRING;
ALTER PROPERTY CUSTOMER_SOUTH.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.LAST_NAME STRING;
ALTER PROPERTY CUSTOMER_SOUTH.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.GENDER STRING;
ALTER PROPERTY CUSTOMER_SOUTH.GENDER NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.BIRTHDAY DATE;
ALTER PROPERTY CUSTOMER_SOUTH.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.CREATE_DATE DATETIME;
ALTER PROPERTY CUSTOMER_SOUTH.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.LOCATION_IP STRING;
ALTER PROPERTY CUSTOMER_SOUTH.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.BROWSER_USED STRING;
ALTER PROPERTY CUSTOMER_SOUTH.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY CUSTOMER_SOUTH.PLACE INTEGER;
ALTER PROPERTY CUSTOMER_SOUTH.PLACE NOTNULL TRUE;

CREATE CLASS PRODUCT EXTENDS V CLUSTER 23;
CREATE PROPERTY PRODUCT.PRODUCT_ID STRING;
ALTER PROPERTY PRODUCT.PRODUCT_ID MANDATORY TRUE;
ALTER PROPERTY PRODUCT.PRODUCT_ID NOTNULL TRUE;
CREATE PROPERTY PRODUCT.TITLE STRING;
ALTER PROPERTY PRODUCT.TITLE NOTNULL TRUE;
CREATE PROPERTY PRODUCT.PRICE FLOAT;
ALTER PROPERTY PRODUCT.PRICE NOTNULL TRUE;
ALTER PROPERTY PRODUCT.PRICE MIN 0;
CREATE PROPERTY PRODUCT.IMG_URL STRING;
ALTER PROPERTY PRODUCT.IMG_URL NOTNULL TRUE;
CREATE PROPERTY PRODUCT.SKU STRING;
ALTER PROPERTY PRODUCT.SKU NOTNULL TRUE;
CREATE PROPERTY PRODUCT.VENDOR_ID LINK VENDOR;  -- Relación a Vendor

CREATE CLASS PRODUCT_CHEAP EXTENDS V CLUSTER 24;
CREATE PROPERTY PRODUCT_CHEAP.PRODUCT_ID STRING;
ALTER PROPERTY PRODUCT_CHEAP.PRODUCT_ID MANDATORY TRUE;
ALTER PROPERTY PRODUCT_CHEAP.PRODUCT_ID NOTNULL TRUE;
CREATE PROPERTY PRODUCT_CHEAP.TITLE STRING;
ALTER PROPERTY PRODUCT_CHEAP.TITLE NOTNULL TRUE;
CREATE PROPERTY PRODUCT_CHEAP.PRICE FLOAT;
ALTER PROPERTY PRODUCT_CHEAP.PRICE NOTNULL TRUE;
ALTER PROPERTY PRODUCT_CHEAP.PRICE MIN 0;
CREATE PROPERTY PRODUCT_CHEAP.IMG_URL STRING;
ALTER PROPERTY PRODUCT_CHEAP.IMG_URL NOTNULL TRUE;
CREATE PROPERTY PRODUCT_CHEAP.SKU STRING;
ALTER PROPERTY PRODUCT_CHEAP.SKU NOTNULL TRUE;
CREATE PROPERTY PRODUCT_CHEAP.VENDOR_ID LINK VENDOR;

CREATE CLASS PRODUCT_EXPENSIVE EXTENDS V CLUSTER 25;
CREATE PROPERTY PRODUCT_EXPENSIVE.PRODUCT_ID STRING;
ALTER PROPERTY PRODUCT_EXPENSIVE.PRODUCT_ID MANDATORY TRUE;
ALTER PROPERTY PRODUCT_EXPENSIVE.PRODUCT_ID NOTNULL TRUE;
CREATE PROPERTY PRODUCT_EXPENSIVE.TITLE STRING;
ALTER PROPERTY PRODUCT_EXPENSIVE.TITLE NOTNULL TRUE;
CREATE PROPERTY PRODUCT_EXPENSIVE.PRICE FLOAT;
ALTER PROPERTY PRODUCT_EXPENSIVE.PRICE NOTNULL TRUE;
ALTER PROPERTY PRODUCT_EXPENSIVE.PRICE MIN 0;
CREATE PROPERTY PRODUCT_EXPENSIVE.IMG_URL STRING;
ALTER PROPERTY PRODUCT_EXPENSIVE.IMG_URL NOTNULL TRUE;
CREATE PROPERTY PRODUCT_EXPENSIVE.SKU STRING;
ALTER PROPERTY PRODUCT_EXPENSIVE.SKU NOTNULL TRUE;
CREATE PROPERTY PRODUCT_EXPENSIVE.VENDOR_ID LINK VENDOR;


--  **Crear Clases Fragmentadas**
CREATE CLASS ORDER_PRE_PANDEMIC EXTENDS V CLUSTER 26;
CREATE PROPERTY ORDER_PRE_PANDEMIC.ORDER_ID STRING;
ALTER PROPERTY ORDER_PRE_PANDEMIC.ORDER_ID MANDATORY TRUE;
ALTER PROPERTY ORDER_PRE_PANDEMIC.ORDER_ID NOTNULL TRUE;
CREATE PROPERTY ORDER_PRE_PANDEMIC.CUSTOMER_ID LINK CUSTOMER;  -- FK a Customer
CREATE PROPERTY ORDER_PRE_PANDEMIC.ORDER_DATE STRING;
ALTER PROPERTY ORDER_PRE_PANDEMIC.ORDER_DATE NOTNULL TRUE;
CREATE PROPERTY ORDER_PRE_PANDEMIC.TOTAL_PRICE FLOAT;
ALTER PROPERTY ORDER_PRE_PANDEMIC.TOTAL_PRICE MIN 0;
ALTER PROPERTY ORDER_PRE_PANDEMIC.TOTAL_PRICE NOTNULL TRUE;
CREATE PROPERTY ORDER_PRE_PANDEMIC.ORDERLINE LINKLIST PRODUCT; 


CREATE CLASS PERSON EXTENDS V CLUSTER 27;
CREATE PROPERTY PERSON.PERSON_ID STRING;
ALTER PROPERTY PERSON.PERSON_ID MANDATORY TRUE;
ALTER PROPERTY PERSON.PERSON_ID NOTNULL TRUE;
CREATE PROPERTY PERSON.FIRST_NAME STRING;
ALTER PROPERTY PERSON.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON.LAST_NAME STRING;
ALTER PROPERTY PERSON.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON.GENDER STRING;
ALTER PROPERTY PERSON.GENDER NOTNULL TRUE;
CREATE PROPERTY PERSON.BIRTHDAY DATE;
ALTER PROPERTY PERSON.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY PERSON.CREATE_DATE DATETIME;
ALTER PROPERTY PERSON.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY PERSON.LOCATION_IP STRING;
ALTER PROPERTY PERSON.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY PERSON.BROWSER_USED STRING;
ALTER PROPERTY PERSON.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY PERSON.PLACE INTEGER;
ALTER PROPERTY PERSON.PLACE NOTNULL TRUE;

CREATE CLASS PERSON_NORTH EXTENDS V CLUSTER 28;
CREATE PROPERTY PERSON_NORTH.PERSON_ID STRING;
ALTER PROPERTY PERSON_NORTH.PERSON_ID MANDATORY TRUE;
ALTER PROPERTY PERSON_NORTH.PERSON_ID NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.FIRST_NAME STRING;
ALTER PROPERTY PERSON_NORTH.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.LAST_NAME STRING;
ALTER PROPERTY PERSON_NORTH.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.GENDER STRING;
ALTER PROPERTY PERSON_NORTH.GENDER NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.BIRTHDAY DATE;
ALTER PROPERTY PERSON_NORTH.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.CREATE_DATE DATETIME;
ALTER PROPERTY PERSON_NORTH.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.LOCATION_IP STRING;
ALTER PROPERTY PERSON_NORTH.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.BROWSER_USED STRING;
ALTER PROPERTY PERSON_NORTH.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY PERSON_NORTH.PLACE INTEGER;
ALTER PROPERTY PERSON_NORTH.PLACE NOTNULL TRUE;

CREATE CLASS PERSON_CENTER EXTENDS V CLUSTER 29;
CREATE PROPERTY PERSON_CENTER.PERSON_ID STRING;
ALTER PROPERTY PERSON_CENTER.PERSON_ID MANDATORY TRUE;
ALTER PROPERTY PERSON_CENTER.PERSON_ID NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.FIRST_NAME STRING;
ALTER PROPERTY PERSON_CENTER.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.LAST_NAME STRING;
ALTER PROPERTY PERSON_CENTER.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.GENDER STRING;
ALTER PROPERTY PERSON_CENTER.GENDER NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.BIRTHDAY DATE;
ALTER PROPERTY PERSON_CENTER.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.CREATE_DATE DATETIME;
ALTER PROPERTY PERSON_CENTER.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.LOCATION_IP STRING;
ALTER PROPERTY PERSON_CENTER.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.BROWSER_USED STRING;
ALTER PROPERTY PERSON_CENTER.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY PERSON_CENTER.PLACE INTEGER;
ALTER PROPERTY PERSON_CENTER.PLACE NOTNULL TRUE;

CREATE CLASS PERSON_SOUTH EXTENDS V CLUSTER 30
CREATE PROPERTY PERSON_SOUTH.PERSON_ID STRING;
ALTER PROPERTY PERSON_SOUTH.PERSON_ID MANDATORY TRUE;
ALTER PROPERTY PERSON_SOUTH.PERSON_ID NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.FIRST_NAME STRING;
ALTER PROPERTY PERSON_SOUTH.FIRST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.LAST_NAME STRING;
ALTER PROPERTY PERSON_SOUTH.LAST_NAME NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.GENDER STRING;
ALTER PROPERTY PERSON_SOUTH.GENDER NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.BIRTHDAY DATE;
ALTER PROPERTY PERSON_SOUTH.BIRTHDAY NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.CREATE_DATE DATETIME;
ALTER PROPERTY PERSON_SOUTH.CREATE_DATE NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.LOCATION_IP STRING;
ALTER PROPERTY PERSON_SOUTH.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.BROWSER_USED STRING;
ALTER PROPERTY PERSON_SOUTH.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY PERSON_SOUTH.PLACE INTEGER;

CREATE CLASS TAG EXTENDS V CLUSTER 31;
CREATE PROPERTY TAG.TAG_ID STRING;
ALTER PROPERTY TAG.TAG_ID MANDATORY TRUE;
ALTER PROPERTY TAG.TAG_ID NOTNULL TRUE;
CREATE PROPERTY TAG.TITLE STRING;
ALTER PROPERTY TAG.TITLE NOTNULL TRUE;

CREATE CLASS POST EXTENDS V CLUSTER 32;
CREATE PROPERTY POST.POST_ID STRING;
ALTER PROPERTY POST.POST_ID MANDATORY TRUE;
ALTER PROPERTY POST.POST_ID NOTNULL TRUE;
CREATE PROPERTY POST.CREATE_DATE DATETIME;
CREATE PROPERTY POST.IMAGE_FILE STRING;
CREATE PROPERTY POST.LOCATION_IP STRING;
ALTER PROPERTY POST.LOCATION_IP NOTNULL TRUE;
CREATE PROPERTY POST.BROWSER_USED STRING;
ALTER PROPERTY POST.BROWSER_USED NOTNULL TRUE;
CREATE PROPERTY POST.CONTENT STRING;
CREATE PROPERTY POST.LENGTH INTEGER;
ALTER PROPERTY POST.LENGTH MIN 0;


--  **Crear Relaciones**
CREATE CLASS CUSTOMER_KNOWS_PERSON EXTENDS E CLUSTER 33;

CREATE CLASS POST_HAS_TAG EXTENDS E CLUSTER 34;

CREATE CLASS PERSON_HAS_INTEREST_TAG EXTENDS E CLUSTER 35;
CREATE CLASS PERSON_NORTH_HAS_INTEREST_TAG EXTENDS E CLUSTER 36;
CREATE CLASS PERSON_CENTER_HAS_INTEREST_TAG EXTENDS E CLUSTER 37;
CREATE CLASS PERSON_SOUTH_HAS_INTEREST_TAG EXTENDS E CLUSTER 38;

CREATE CLASS POST_HAS_CREATOR_PERSON EXTENDS E CLUSTER 39;
CREATE CLASS POST_HAS_CREATOR_PERSON_NORTH EXTENDS E CLUSTER 40;
CREATE CLASS POST_HAS_CREATOR_PERSON_CENTER EXTENDS E CLUSTER 41;
CREATE CLASS POST_HAS_CREATOR_PERSON_SOUTH EXTENDS E CLUSTER 42;

--  **Confirmación de Clases y Propiedades**
INFO